fn=input()
s1=input()
s2=input()
f=open(fn, "r", encoding="utf-8")
print('=== Before the replacement')
datas=f.read()
print(datas)
datas=datas.replace(s1, s2)
print('=== After the replacement')
print(datas)
f.close()